"""Single source of truth and drift detection.

Benchmark Defect One is the ambiguity that arises when a graphical layer owns a
database and the engine owns text files.  This module removes the ambiguity by
declaring one structured document to be the source of truth and every engine
configuration file to be a rendered artefact of it.

Before rendering, the digest of each artefact on disk is compared with the
digest recorded when the appliance last wrote it.  A mismatch means a human
edited a generated file.  The store then refuses to overwrite and raises the
divergence for an explicit reconciliation decision: adopt what is on disk, or
regenerate over it.  Drift is reported, never resolved by ambush.

Writes are atomic — render to a temporary file in the same directory,
synchronise it, then rename — so an interrupted write cannot leave the engine
reading a half written configuration.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Mapping

from . import PRODUCT_NAME
from .logging_setup import get_logger

__all__ = [
    "ConfigurationStore",
    "DriftReport",
    "DriftDetected",
    "GENERATED_MARKER",
]

_LOG = get_logger("confstore")

GENERATED_MARKER = "generated by the appliance control plane -- do not edit by hand"

STATUS_CURRENT = "current"
STATUS_MODIFIED = "modified"
STATUS_MISSING = "missing"
STATUS_UNMANAGED = "unmanaged"

_DEFAULT_DOCUMENT: dict[str, Any] = {
    "revision": 1,
    "site": {"name": "an unnamed site", "timezone": "UTC"},
    "trunks": [],
    "extensions": [],
    "ring_groups": [],
    "inbound_routes": [],
    "outbound_routes": [],
    "time_conditions": [],
    "ivr_menus": [],
    "queues": [],
    "conferences": [],
    "dialplan": {"inbound_context": "from-trunk", "internal_context": "internal"},
    "hardware": {"spans": []},
}


class DriftDetected(RuntimeError):
    """Raised when a generated artefact was modified outside the appliance."""

    def __init__(self, reports: list["DriftReport"]) -> None:
        self.reports = list(reports)
        names = ", ".join(report.name for report in self.reports)
        super().__init__(
            "one or more generated configuration files were modified outside the "
            f"appliance and will not be overwritten without a decision: {names}"
        )


@dataclass(frozen=True)
class DriftReport:
    """The reconciliation state of one generated artefact."""

    name: str
    path: str
    status: str
    recorded_digest: str | None = None
    actual_digest: str | None = None

    @property
    def diverged(self) -> bool:
        return self.status in (STATUS_MODIFIED, STATUS_UNMANAGED)

    def as_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["diverged"] = self.diverged
        return payload



class DocumentRefused(ValueError):
    """The source of truth carried something that must never be rendered."""


#: Characters that end a line, or terminate a string, in the files rendered
#: from this document.  A value containing one of these is not a value.
_STRUCTURAL = re.compile(r"[\r\n\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def reject_structural_values(document: Any, _path: str = "") -> None:
    """Refuse a document carrying a value that could become an instruction.

    This is the last line rather than the first.  The entity routes validate
    every field against the schema, and they should; this exists because the
    rendered artefacts are loaded by root, and a defence that lives only at the
    door somebody remembered to lock is not a defence.  Walking the whole
    document costs nothing at the rate configurations are saved.

    Refusal is deliberate rather than escaping.  There is no legitimate reason
    for a trunk name or a route destination to contain a newline, so a document
    that carries one is either a defect or an attack, and quietly repairing
    either would hide it.
    """
    if isinstance(document, Mapping):
        for key, value in document.items():
            reject_structural_values(value, f"{_path}.{key}" if _path else str(key))
    elif isinstance(document, (list, tuple)):
        for index, value in enumerate(document):
            reject_structural_values(value, f"{_path}[{index}]")
    elif isinstance(document, str):
        match = _STRUCTURAL.search(document)
        if match:
            where = _path or "a value"
            raise DocumentRefused(
                f"the value at {where} contains a character that would end a "
                f"line in a generated file; a name or a destination cannot "
                f"contain one"
            )

class ConfigurationStore:
    """Owns the source of truth document and the artefacts rendered from it."""

    def __init__(
        self,
        document_path: str | Path,
        output_directory: str | Path,
        digest_path: str | Path,
        secrets: Any = None,
    ) -> None:
        self.document_path = Path(document_path)
        self.output_directory = Path(output_directory)
        self.digest_path = Path(digest_path)
        #: Secrets are held apart from the source of truth and are read only
        #: here, at the moment an artefact is rendered.
        self.secrets = secrets

    # -- the source of truth ------------------------------------------------

    def load(self) -> dict[str, Any]:
        """Load the source of truth, returning defaults when it is absent."""
        if not self.document_path.is_file():
            return json.loads(json.dumps(_DEFAULT_DOCUMENT))
        try:
            raw = json.loads(self.document_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise DriftDetected(
                [
                    DriftReport(
                        name="the source of truth document",
                        path=str(self.document_path),
                        status=STATUS_MODIFIED,
                        actual_digest=None,
                    )
                ]
            ) from error
        if not isinstance(raw, dict):
            raise ValueError("the source of truth document must be a mapping")

        document = json.loads(json.dumps(_DEFAULT_DOCUMENT))
        document.update(raw)
        return document

    def save(self, document: Mapping[str, Any]) -> dict[str, Any]:
        """Persist the source of truth atomically, bumping its revision.

        Everything written here is later spliced, as literal text, into files
        that root loads: the firewall ruleset and the telephony engine's
        dialplan.  A value carrying a newline therefore stops being a value and
        becomes a line, and a line in either of those files is an instruction.

        That was not hypothetical.  A document posted to this route with a
        newline inside a route's destination reached the dialplan as
        ``same => n,System(...)``, which the engine executes; another with a
        newline inside a firewall rule's name reached the ruleset as a
        redirection chain sending call signalling to a chosen host, and it
        passed the syntax check the privileged helper gates on because it was
        perfectly valid syntax. The entity routes validated their input against
        the schema and this one did not, so the same value refused at one door
        was accepted at the other.
        """
        reject_structural_values(document)
        payload = dict(document)
        payload["revision"] = int(payload.get("revision", 0)) + 1
        payload["updated_at"] = time.time()
        _atomic_write(self.document_path, json.dumps(payload, indent=2, sort_keys=True))
        _LOG.info(
            "the source of truth document was saved at revision number %d",
            payload["revision"],
        )
        return payload

    # -- rendering ----------------------------------------------------------

    def artefacts(self, document: Mapping[str, Any] | None = None) -> dict[str, str]:
        """Render every engine configuration artefact into memory.

        The document is checked again here, not only when it was saved. A
        document can reach this point without passing through save -- edited on
        disk during a recovery, restored from a backup, or written by a future
        route -- and rendering is the moment before root reads the result.
        """
        source = document if document is not None else self.load()
        reject_structural_values(source)
        return {
            "pjsip.conf": render_endpoints(source, self.secrets),
            "extensions.conf": render_dialplan(source),
            "voicemail.conf": render_voicemail(source, self.secrets),
            "queues.conf": render_queues(source),
            "confbridge.conf": render_conferences(source, self.secrets),
            "chan_dahdi.conf": render_hardware_channels(source),
            "manager.conf": render_manager_interface(source),
        }

    def inspect(self, document: Mapping[str, Any] | None = None) -> list[DriftReport]:
        """Report the reconciliation state of every artefact without writing."""
        recorded = self._load_digests()
        reports: list[DriftReport] = []

        for name in self.artefacts(document):
            path = self.output_directory / name
            expected = recorded.get(name)

            if not path.is_file():
                status = STATUS_MISSING
                actual = None
            else:
                actual = _digest(path.read_bytes())
                if expected is None:
                    # A file the appliance has never written is not the
                    # appliance's to overwrite.
                    status = STATUS_UNMANAGED
                elif actual == expected:
                    status = STATUS_CURRENT
                else:
                    status = STATUS_MODIFIED

            reports.append(
                DriftReport(
                    name=name,
                    path=str(path),
                    status=status,
                    recorded_digest=expected,
                    actual_digest=actual,
                )
            )
        return reports

    def render(
        self,
        document: Mapping[str, Any] | None = None,
        force: bool = False,
    ) -> dict[str, Any]:
        """Write every artefact, refusing to overwrite a diverged file.

        With ``force`` the divergence is overwritten deliberately, which is the
        regenerate arm of the reconciliation decision.  The refusal path is the
        default because losing an administrator's emergency edit without
        telling them is the exact failure this product exists to remove.
        """
        source = document if document is not None else self.load()
        rendered = self.artefacts(source)
        reports = self.inspect(source)
        diverged = [report for report in reports if report.diverged]

        if diverged and not force:
            for report in diverged:
                _LOG.error(
                    "the generated file named %s diverged from the appliance record "
                    "and was not overwritten",
                    report.name,
                )
            raise DriftDetected(diverged)

        self.output_directory.mkdir(parents=True, exist_ok=True)
        digests = self._load_digests()
        written: list[str] = []

        for name, content in rendered.items():
            path = self.output_directory / name
            digest = _digest(content.encode("utf-8"))
            if path.is_file() and _digest(path.read_bytes()) == digest:
                # Identical content is not rewritten, so an unchanged render
                # does not disturb file timestamps the engine may watch.
                digests[name] = digest
                continue
            _atomic_write(path, content)
            digests[name] = digest
            written.append(name)

        self._save_digests(digests)
        if written:
            _LOG.info(
                "the appliance rendered %d configuration file or files: %s",
                len(written),
                ", ".join(written),
            )
        return {
            "written": written,
            "unchanged": [name for name in rendered if name not in written],
            "forced": bool(force and diverged),
            "reports": [report.as_dict() for report in reports],
        }

    def adopt(self, name: str) -> DriftReport:
        """Accept the on disk version of an artefact as the current record.

        This is the adopt arm of the reconciliation decision.  The appliance
        records the administrator's file as authoritative, which stops the
        divergence being reported without destroying the edit.
        """
        path = self.output_directory / name
        if not path.is_file():
            raise FileNotFoundError(f"there is no artefact named {name} to adopt")

        digests = self._load_digests()
        actual = _digest(path.read_bytes())
        digests[name] = actual
        self._save_digests(digests)
        _LOG.warning(
            "the on disk version of the file named %s was adopted as authoritative; "
            "the appliance will no longer report it as diverged",
            name,
        )
        return DriftReport(
            name=name,
            path=str(path),
            status=STATUS_CURRENT,
            recorded_digest=actual,
            actual_digest=actual,
        )

    # -- digest bookkeeping -------------------------------------------------

    def _load_digests(self) -> dict[str, str]:
        if not self.digest_path.is_file():
            return {}
        try:
            data = json.loads(self.digest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            _LOG.warning(
                "the rendered file digest record could not be read; every generated "
                "file will be treated as unmanaged until it is reconciled"
            )
            return {}
        return {str(key): str(value) for key, value in data.items()} if isinstance(data, dict) else {}

    def _save_digests(self, digests: Mapping[str, str]) -> None:
        _atomic_write(self.digest_path, json.dumps(dict(digests), indent=2, sort_keys=True))


# -- renderers -------------------------------------------------------------


def _header(title: str) -> str:
    return (
        f"; {title}\n"
        f"; {GENERATED_MARKER}\n"
        "; edits made here are detected by the appliance and raised for an\n"
        "; explicit reconciliation decision rather than being silently replaced.\n"
        ";\n"
        "; this appliance assigns no addresses: it contains no address allocation\n"
        "; service of any kind, by specification.\n"
        "\n"
    )


def _secret_for(secrets: Any, kind: str, key: str, field_name: str) -> str | None:
    if secrets is None:
        return None
    try:
        return secrets.get(kind, key, field_name)
    except Exception:  # noqa: BLE001 - a secret store fault must not stop a render
        _LOG.error("a secret could not be read while rendering; the entry is omitted")
        return None


def _enabled(record: Mapping[str, Any]) -> bool:
    return bool(record.get("enabled", True))


def render_endpoints(document: Mapping[str, Any], secrets: Any = None) -> str:
    """Render every trunk and every telephone for the session channel driver."""
    dialplan = document.get("dialplan", {}) or {}
    inbound_context = str(dialplan.get("inbound_context", "from-trunk"))
    internal_context = str(dialplan.get("internal_context", "internal"))

    lines = [_header("trunks and telephones")]
    lines.append("[global]\n")
    lines.append("type = global\n")
    lines.append(f"user_agent = {PRODUCT_NAME}\n\n")

    lines.append("; ------------------------------------------------------------\n")
    lines.append("; trunks\n")
    lines.append("; ------------------------------------------------------------\n\n")

    for trunk in document.get("trunks", []) or []:
        name = str(trunk.get("name", "")).strip()
        if not name or not _enabled(trunk):
            continue
        if str(trunk.get("technology", "PJSIP")).upper() != "PJSIP":
            lines.append(f"; the trunk named {name} uses another channel technology\n\n")
            continue

        host = str(trunk.get("host", "")).strip()
        username = str(trunk.get("username", "")).strip()
        secret = _secret_for(secrets, "trunks", name, "secret")

        if trunk.get("register", True) and username:
            lines.append(f"[{name}]\n")
            lines.append("type = registration\n")
            lines.append(f"outbound_auth = {name}-auth\n")
            lines.append(f"server_uri = sip:{host}\n")
            lines.append(f"client_uri = sip:{username}@{host}\n")
            lines.append("retry_interval = 60\n")
            lines.append("forbidden_retry_interval = 600\n")
            lines.append("expiration = 3600\n\n")

        if username:
            lines.append(f"[{name}-auth]\n")
            lines.append("type = auth\n")
            lines.append("auth_type = userpass\n")
            lines.append(f"username = {username}\n")
            if secret:
                lines.append(f"password = {secret}\n")
            else:
                lines.append("; no password has been set for this trunk yet\n")
            lines.append("\n")

        lines.append(f"[{name}-endpoint]\n")
        lines.append("type = endpoint\n")
        lines.append(f"context = {inbound_context}\n")
        lines.append("disallow = all\n")
        lines.append("allow = ulaw,alaw\n")
        if username:
            lines.append(f"outbound_auth = {name}-auth\n")
        lines.append(f"aors = {name}-aor\n")
        lines.append("direct_media = no\n\n")

        lines.append(f"[{name}-aor]\n")
        lines.append("type = aor\n")
        lines.append(f"contact = sip:{host}\n")
        lines.append("qualify_frequency = 60\n\n")

        lines.append(f"[{name}-identify]\n")
        lines.append("type = identify\n")
        lines.append(f"endpoint = {name}-endpoint\n")
        lines.append(f"match = {host}\n\n")

    lines.append("; ------------------------------------------------------------\n")
    lines.append("; telephones\n")
    lines.append("; ------------------------------------------------------------\n\n")

    for extension in document.get("extensions", []) or []:
        number = str(extension.get("number", "")).strip()
        if not number or not _enabled(extension):
            continue
        if str(extension.get("technology", "PJSIP")).upper() != "PJSIP":
            lines.append(f"; the extension numbered {number} uses another channel technology\n\n")
            continue

        name = str(extension.get("name", "")).strip() or f"extension {number}"
        secret = _secret_for(secrets, "extensions", number, "secret")

        lines.append(f"[{number}]\n")
        lines.append("type = endpoint\n")
        lines.append(f"context = {internal_context}\n")
        lines.append("disallow = all\n")
        lines.append("allow = ulaw,alaw\n")
        lines.append(f"auth = {number}-auth\n")
        lines.append(f"aors = {number}\n")
        lines.append(f"callerid = {name} <{number}>\n")
        if extension.get("voicemail", True):
            lines.append(f"mailboxes = {number}@default\n")
        lines.append("direct_media = no\n\n")

        lines.append(f"[{number}-auth]\n")
        lines.append("type = auth\n")
        lines.append("auth_type = userpass\n")
        lines.append(f"username = {number}\n")
        if secret:
            lines.append(f"password = {secret}\n")
        else:
            lines.append("; no password has been set for this telephone yet\n")
        lines.append("\n")

        lines.append(f"[{number}]\n")
        lines.append("type = aor\n")
        lines.append("max_contacts = 2\n")
        lines.append("remove_existing = yes\n\n")

    return "".join(lines)


_DAY_NAMES = {
    "mon": "mon", "tue": "tue", "wed": "wed", "thu": "thu",
    "fri": "fri", "sat": "sat", "sun": "sun",
}


def _destination_lines(kind: str, value: str, internal: str) -> list[str]:
    """Render a jump to whatever destination an operator chose."""
    kind = (kind or "extension").strip().lower()
    value = str(value or "").strip()

    if kind == "hang up" or not value:
        return [" same => n,Hangup()\n"]
    if kind == "voicemail":
        return [f" same => n,VoiceMail({value}@default,u)\n", " same => n,Hangup()\n"]
    # Every other destination -- an extension, a ring group, a queue, a menu,
    # a conference room -- is reached by its number in the internal context.
    # That is what keeps this table small and the dialplan uniform: one number
    # space, and the object that owns the number decides what happens.
    return [f" same => n,Goto({internal},{value},1)\n"]


def _parse_options(text: str) -> list[tuple[str, str]]:
    """Read a menu's options into key and destination pairs."""
    pairs: list[tuple[str, str]] = []
    for entry in str(text or "").split(","):
        key, separator, destination = entry.partition("=")
        if separator and key.strip() and destination.strip():
            pairs.append((key.strip(), destination.strip()))
    return pairs


def render_dialplan(document: Mapping[str, Any]) -> str:
    """Render the complete dialplan from every declared object."""
    dialplan = document.get("dialplan", {}) or {}
    internal = str(dialplan.get("internal_context", "internal"))
    inbound = str(dialplan.get("inbound_context", "from-trunk"))

    lines = [_header("dialplan")]

    # -- telephones ------------------------------------------------------
    lines.append(f"[{internal}]\n")
    lines.append("; telephones\n")
    for extension in document.get("extensions", []) or []:
        number = str(extension.get("number", "")).strip()
        if not number or not _enabled(extension):
            continue
        technology = str(extension.get("technology", "PJSIP")).upper()
        ring = int(extension.get("ring_seconds", 20) or 20)

        lines.append(f"exten => {number},1,NoOp(a call to the extension {number})\n")
        lines.append(f" same => n,Dial({technology}/{number},{ring})\n")
        if extension.get("voicemail", True):
            lines.append(f" same => n,VoiceMail({number}@default,u)\n")
        lines.append(" same => n,Hangup()\n\n")

    # -- ring groups -------------------------------------------------------
    groups = [group for group in document.get("ring_groups", []) or [] if _enabled(group)]
    if groups:
        lines.append("; ring groups\n")
    for group in groups:
        number = str(group.get("number", "")).strip()
        members = [str(member).strip() for member in group.get("members", []) or []]
        if not number or not members:
            continue
        ring = int(group.get("ring_seconds", 25) or 25)
        strategy = str(group.get("strategy", "ring all")).lower()

        lines.append(f"exten => {number},1,NoOp(a call to the ring group {number})\n")
        if strategy == "in order":
            for member in members:
                lines.append(f" same => n,Dial(PJSIP/{member},{ring})\n")
        else:
            targets = "&".join(f"PJSIP/{member}" for member in members)
            lines.append(f" same => n,Dial({targets},{ring})\n")
        lines.append(" same => n,Hangup()\n\n")

    # -- time conditions ---------------------------------------------------
    conditions = [
        condition for condition in document.get("time_conditions", []) or []
        if _enabled(condition)
    ]
    if conditions:
        lines.append("; time conditions\n")
    for condition in conditions:
        name = str(condition.get("name", "")).strip()
        if not name:
            continue
        days = [
            _DAY_NAMES[str(day).lower()]
            for day in condition.get("days", []) or []
            if str(day).lower() in _DAY_NAMES
        ]
        day_range = "&".join(days) if days else "mon-fri"
        starts = str(condition.get("starts_at", "09:00"))
        ends = str(condition.get("ends_at", "17:30"))

        lines.append(f"exten => {name},1,NoOp(the time condition named {name})\n")
        lines.append(
            f" same => n,GotoIfTime({starts}-{ends},{day_range},*,*?{name}-open,1)\n"
        )
        lines.append(f" same => n,Goto({name}-closed,1)\n\n")

        lines.append(f"exten => {name}-open,1,NoOp(inside the opening hours)\n")
        lines.extend(
            _destination_lines("extension", condition.get("open_destination", ""), internal)
        )
        lines.append("\n")
        lines.append(f"exten => {name}-closed,1,NoOp(outside the opening hours)\n")
        lines.extend(
            _destination_lines("extension", condition.get("closed_destination", ""), internal)
        )
        lines.append("\n")

    # -- interactive menus -------------------------------------------------
    menus = [menu for menu in document.get("ivr_menus", []) or [] if _enabled(menu)]
    if menus:
        lines.append("; interactive menus\n")
    for menu in menus:
        number = str(menu.get("number", "")).strip()
        options = _parse_options(menu.get("options", ""))
        if not number or not options:
            continue

        greeting = str(menu.get("greeting", "") or "vm-enter-num-to-call")
        wait = int(menu.get("wait_seconds", 10) or 10)

        lines.append(f"exten => {number},1,NoOp(the menu numbered {number})\n")
        lines.append(" same => n,Answer()\n")
        lines.append(f" same => n,Background({greeting})\n")
        lines.append(f" same => n,WaitExten({wait})\n\n")

        for key, destination in options:
            lines.append(
                f"exten => {number}-{key},1,NoOp(the caller chose {key} at the menu "
                f"numbered {number})\n"
            )
            lines.append(f" same => n,Goto({internal},{destination},1)\n\n")

        # The engine matches the pressed key inside the menu's own extension,
        # so each key is bridged to the option written above.
        for key, _ in options:
            lines.append(f"exten => {key},1,NoOp(a key pressed at a menu)\n")
            lines.append(f" same => n,Goto({internal},{number}-{key},1)\n\n")

        fallback = str(menu.get("timeout_destination", "") or "").strip()
        for label in ("t", "i"):
            lines.append(
                f"exten => {number}-{label},1,NoOp(no usable choice was made at the "
                f"menu numbered {number})\n"
            )
            if fallback:
                lines.append(f" same => n,Goto({internal},{fallback},1)\n\n")
            else:
                lines.append(" same => n,Hangup()\n\n")

    # -- queues -------------------------------------------------------------
    queues = [queue for queue in document.get("queues", []) or [] if _enabled(queue)]
    if queues:
        lines.append("; queues\n")
    for queue in queues:
        number = str(queue.get("number", "")).strip()
        if not number:
            continue
        overflow = str(queue.get("overflow_destination", "") or "").strip()

        lines.append(f"exten => {number},1,NoOp(a call to the queue numbered {number})\n")
        lines.append(" same => n,Answer()\n")
        lines.append(f" same => n,Queue({number},t)\n")
        if overflow:
            lines.append(f" same => n,Goto({internal},{overflow},1)\n")
        else:
            lines.append(" same => n,Hangup()\n")
        lines.append("\n")

    # -- conference rooms ----------------------------------------------------
    rooms = [room for room in document.get("conferences", []) or [] if _enabled(room)]
    if rooms:
        lines.append("; conference rooms\n")
    for room in rooms:
        number = str(room.get("number", "")).strip()
        if not number:
            continue
        lines.append(f"exten => {number},1,NoOp(a call to the conference room numbered {number})\n")
        lines.append(" same => n,Answer()\n")
        lines.append(f" same => n,ConfBridge({number},{number}-bridge,{number}-user)\n")
        lines.append(" same => n,Hangup()\n\n")

    # -- outbound routes ---------------------------------------------------
    routes = sorted(
        (route for route in document.get("outbound_routes", []) or [] if _enabled(route)),
        key=lambda route: int(route.get("priority", 10) or 10),
    )
    if routes:
        lines.append("; outbound routes, in the order they are tried\n")
    for route in routes:
        pattern = str(route.get("pattern", "")).strip()
        trunk = str(route.get("trunk", "")).strip()
        if not pattern or not trunk:
            continue

        strip = int(route.get("strip_digits", 0) or 0)
        prepend = str(route.get("prepend_digits", "") or "")
        dialled = "${EXTEN}"
        if strip:
            dialled = f"${{EXTEN:{strip}}}"
        if prepend:
            dialled = f"{prepend}{dialled}"

        lines.append(
            f"exten => _{pattern},1,NoOp(an outbound call by the route named "
            f"{route.get('name', 'unnamed')})\n"
        )
        lines.append(f" same => n,Dial(PJSIP/{dialled}@{trunk}-endpoint,60)\n")
        lines.append(" same => n,Congestion(5)\n")
        lines.append(" same => n,Hangup()\n\n")

    # -- inbound routes ----------------------------------------------------
    lines.append(f"\n[{inbound}]\n")
    inbound_routes = [
        route for route in document.get("inbound_routes", []) or [] if _enabled(route)
    ]
    if not inbound_routes:
        lines.append("exten => _.,1,NoOp(an inbound call with no route configured)\n")
        lines.append(" same => n,Congestion(5)\n")
        lines.append(" same => n,Hangup()\n\n")
        return "".join(lines)

    for route in inbound_routes:
        did = str(route.get("did", "")).strip()
        if not did:
            continue
        # A route for anything is written as a pattern; an exact number is not.
        label = f"_{did}" if any(mark in did for mark in "._NXZ[]") else did
        description = str(route.get("description", "")).strip() or "an inbound call"

        lines.append(f"exten => {label},1,NoOp({description})\n")
        lines.extend(
            _destination_lines(
                str(route.get("destination_kind", "extension")),
                route.get("destination_value", ""),
                internal,
            )
        )
        lines.append(" same => n,Hangup()\n\n")

    return "".join(lines)


_QUEUE_STRATEGIES = {
    "ring all": "ringall",
    "least recent": "leastrecent",
    "fewest calls": "fewestcalls",
    "random": "random",
    "round robin memory": "rrmemory",
}


def render_queues(document: Mapping[str, Any]) -> str:
    """Render every queue and the members that answer it."""
    lines = [_header("queues")]
    lines.append("[general]\n")
    lines.append("persistentmembers = yes\n")
    lines.append("monitor-type = MixMonitor\n\n")

    queues = [queue for queue in document.get("queues", []) or [] if _enabled(queue)]
    if not queues:
        lines.append("; no queue is configured on this system\n")
        return "".join(lines)

    for queue in queues:
        number = str(queue.get("number", "")).strip()
        if not number:
            continue
        strategy = _QUEUE_STRATEGIES.get(
            str(queue.get("strategy", "ring all")).lower(), "ringall"
        )

        lines.append(f"[{number}]\n")
        lines.append(f"; {queue.get('name', 'an unnamed queue')}\n")
        lines.append(f"strategy = {strategy}\n")
        lines.append(f"timeout = {int(queue.get('ring_seconds', 20) or 20)}\n")
        lines.append(f"musicclass = {queue.get('music_class', 'default')}\n")
        # The engine counts against this itself and writes it into the
        # queue log, so the report and the engine agree about what "in
        # time" means rather than each having its own opinion.
        lines.append(
            f"servicelevel = {int(queue.get('service_level_seconds', 20) or 20)}\n"
        )
        lines.append("retry = 5\n")
        lines.append("wrapuptime = 5\n")
        lines.append("joinempty = yes\n")
        lines.append("leavewhenempty = no\n")
        lines.append("ringinuse = no\n")

        maximum = int(queue.get("maximum_waiting", 0) or 0)
        if maximum:
            lines.append(f"maxlen = {maximum}\n")

        for member in queue.get("members", []) or []:
            lines.append(f"member => PJSIP/{str(member).strip()}\n")
        lines.append("\n")

    return "".join(lines)


def render_conferences(document: Mapping[str, Any], secrets: Any = None) -> str:
    """Render every conference room, its bridge, and its user profile."""
    lines = [_header("conference rooms")]

    rooms = [room for room in document.get("conferences", []) or [] if _enabled(room)]
    if not rooms:
        lines.append("; no conference room is configured on this system\n")
        return "".join(lines)

    for room in rooms:
        number = str(room.get("number", "")).strip()
        if not number:
            continue
        pin = _secret_for(secrets, "conferences", number, "pin")

        lines.append(f"[{number}-bridge]\n")
        lines.append("type = bridge\n")
        lines.append(f"; {room.get('name', 'an unnamed room')}\n")
        lines.append("max_members = 50\n")
        lines.append("record_conference = no\n\n")

        lines.append(f"[{number}-user]\n")
        lines.append("type = user\n")
        lines.append(
            f"announce_join_leave = {'yes' if room.get('announce_arrivals', True) else 'no'}\n"
        )
        lines.append(f"music_on_hold_class = {room.get('music_class', 'default')}\n")
        if pin:
            lines.append(f"pin = {pin}\n")
        else:
            lines.append("; this room has no entry code and is open to any caller\n")
        lines.append("dsp_drop_silence = yes\n\n")

    return "".join(lines)


def render_voicemail(document: Mapping[str, Any], secrets: Any = None) -> str:
    """Render the mailboxes for every telephone that has voicemail."""
    lines = [_header("mailboxes")]
    lines.append("[general]\n")
    lines.append("format = wav49|gsm|wav\n")
    lines.append("attach = yes\n")
    lines.append("maxmsg = 100\n")
    lines.append("maxsecs = 300\n")
    lines.append("emailsubject = a message from ${VM_CALLERID}\n")
    lines.append("emailbody = a message of ${VM_DUR} was left in mailbox ${VM_MAILBOX}\n\n")

    lines.append("[default]\n")
    any_mailbox = False
    for extension in document.get("extensions", []) or []:
        number = str(extension.get("number", "")).strip()
        if not number or not _enabled(extension) or not extension.get("voicemail", True):
            continue
        any_mailbox = True

        name = str(extension.get("name", "")).strip() or f"extension {number}"
        address = str(extension.get("electronic_mail", "") or "")
        code = _secret_for(secrets, "extensions", number, "voicemail_password") or ""
        lines.append(f"{number} => {code},{name},{address}\n")

    if not any_mailbox:
        lines.append("; no telephone on this system has voicemail enabled\n")
    return "".join(lines)


def render_hardware_channels(document: Mapping[str, Any]) -> str:
    """Render the legacy interface card channel configuration."""
    hardware = document.get("hardware", {}) or {}
    dialplan = document.get("dialplan", {}) or {}
    context = str(dialplan.get("inbound_context", "from-trunk"))

    lines = [_header("legacy interface card channels")]
    lines.append("[channels]\n")
    lines.append("language = en\n")
    lines.append(f"context = {context}\n")
    lines.append("signalling = fxo_ks\n")
    lines.append("echocancel = yes\n")
    lines.append("echocancelwhenbridged = no\n")
    lines.append("rxgain = 0.0\n")
    lines.append("txgain = 0.0\n")
    lines.append("immediate = no\n\n")

    spans = hardware.get("spans", []) or []
    if not spans:
        lines.append("; no span has been mapped to a logical trunk yet.  run the guided\n")
        lines.append("; hardware bring up from the dashboard to map detected spans.\n")
        return "".join(lines)

    for span in spans:
        number = span.get("number")
        signalling = str(span.get("signalling", "fxo_ks"))
        channels = str(span.get("channels", "")).strip()
        if number is None or not channels:
            continue
        lines.append(f"; span number {number}\n")
        lines.append(f"signalling = {signalling}\n")
        group = span.get("group")
        if group is not None:
            lines.append(f"group = {group}\n")
        lines.append(f"channel => {channels}\n\n")

    return "".join(lines)


def render_manager_interface(document: Mapping[str, Any]) -> str:
    """Render the engine manager interface configuration.

    The interface is bound to the loopback address only.  The control plane is
    the sole consumer and it runs on the same machine, so exposing the manager
    interface to the network would add risk and no capability.
    """
    manager = document.get("manager", {}) or {}
    username = str(manager.get("username", "crossbar"))

    lines = [_header("engine manager interface")]
    lines.append("[general]\n")
    lines.append("enabled = yes\n")
    lines.append("webenabled = no\n")
    lines.append("port = 5038\n")
    lines.append("bindaddr = 127.0.0.1\n")
    lines.append("displayconnects = yes\n")
    lines.append("timestampevents = yes\n\n")

    lines.append(f"[{username}]\n")
    lines.append("; the secret is injected at deployment time and is never rendered here\n")
    lines.append("deny = 0.0.0.0/0.0.0.0\n")
    lines.append("permit = 127.0.0.1/255.255.255.255\n")
    lines.append("read = system,call,log,verbose,agent,user,config,dtmf,reporting,cdr,dialplan\n")
    lines.append("write = system,call,agent,user,config,command,reporting,originate\n")
    return "".join(lines)


# -- helpers ---------------------------------------------------------------


def _digest(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _atomic_write(path: Path, content: str) -> None:
    """Write a file atomically within its own directory."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".partial")
    try:
        with open(temporary, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
