"""Single source of truth and drift detection.

Benchmark Defect One is the ambiguity that arises when a graphical layer owns a
database and the engine owns text files.  This module removes the ambiguity by
declaring one structured document to be the source of truth and every engine
configuration file to be a rendered artefact of it.

Before rendering, the digest of each artefact on disk is compared with the
digest recorded when the appliance last wrote it.  A mismatch means a human
edited a generated file.  The store then refuses to overwrite and raises the
divergence for an explicit reconciliation decision: adopt what is on disk, or
regenerate over it.  Drift is reported, never resolved by ambush.

Writes are atomic — render to a temporary file in the same directory,
synchronise it, then rename — so an interrupted write cannot leave the engine
reading a half written configuration.
"""

from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Mapping

from .logging_setup import get_logger

__all__ = [
    "ConfigurationStore",
    "DriftReport",
    "DriftDetected",
    "GENERATED_MARKER",
]

_LOG = get_logger("confstore")

GENERATED_MARKER = "generated by the appliance control plane -- do not edit by hand"

STATUS_CURRENT = "current"
STATUS_MODIFIED = "modified"
STATUS_MISSING = "missing"
STATUS_UNMANAGED = "unmanaged"

_DEFAULT_DOCUMENT: dict[str, Any] = {
    "revision": 1,
    "site": {"name": "an unnamed site", "timezone": "UTC"},
    "trunks": [],
    "extensions": [],
    "dialplan": {"inbound_context": "from-trunk", "internal_context": "internal"},
    "hardware": {"spans": []},
}


class DriftDetected(RuntimeError):
    """Raised when a generated artefact was modified outside the appliance."""

    def __init__(self, reports: list["DriftReport"]) -> None:
        self.reports = list(reports)
        names = ", ".join(report.name for report in self.reports)
        super().__init__(
            "one or more generated configuration files were modified outside the "
            f"appliance and will not be overwritten without a decision: {names}"
        )


@dataclass(frozen=True)
class DriftReport:
    """The reconciliation state of one generated artefact."""

    name: str
    path: str
    status: str
    recorded_digest: str | None = None
    actual_digest: str | None = None

    @property
    def diverged(self) -> bool:
        return self.status in (STATUS_MODIFIED, STATUS_UNMANAGED)

    def as_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["diverged"] = self.diverged
        return payload


class ConfigurationStore:
    """Owns the source of truth document and the artefacts rendered from it."""

    def __init__(
        self,
        document_path: str | Path,
        output_directory: str | Path,
        digest_path: str | Path,
    ) -> None:
        self.document_path = Path(document_path)
        self.output_directory = Path(output_directory)
        self.digest_path = Path(digest_path)

    # -- the source of truth ------------------------------------------------

    def load(self) -> dict[str, Any]:
        """Load the source of truth, returning defaults when it is absent."""
        if not self.document_path.is_file():
            return json.loads(json.dumps(_DEFAULT_DOCUMENT))
        try:
            raw = json.loads(self.document_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise DriftDetected(
                [
                    DriftReport(
                        name="the source of truth document",
                        path=str(self.document_path),
                        status=STATUS_MODIFIED,
                        actual_digest=None,
                    )
                ]
            ) from error
        if not isinstance(raw, dict):
            raise ValueError("the source of truth document must be a mapping")

        document = json.loads(json.dumps(_DEFAULT_DOCUMENT))
        document.update(raw)
        return document

    def save(self, document: Mapping[str, Any]) -> dict[str, Any]:
        """Persist the source of truth atomically, bumping its revision."""
        payload = dict(document)
        payload["revision"] = int(payload.get("revision", 0)) + 1
        payload["updated_at"] = time.time()
        _atomic_write(self.document_path, json.dumps(payload, indent=2, sort_keys=True))
        _LOG.info(
            "the source of truth document was saved at revision number %d",
            payload["revision"],
        )
        return payload

    # -- rendering ----------------------------------------------------------

    def artefacts(self, document: Mapping[str, Any] | None = None) -> dict[str, str]:
        """Render every engine configuration artefact into memory."""
        source = document if document is not None else self.load()
        return {
            "pjsip.conf": render_trunk_configuration(source),
            "extensions.conf": render_dialplan(source),
            "chan_dahdi.conf": render_hardware_channels(source),
            "manager.conf": render_manager_interface(source),
        }

    def inspect(self, document: Mapping[str, Any] | None = None) -> list[DriftReport]:
        """Report the reconciliation state of every artefact without writing."""
        recorded = self._load_digests()
        reports: list[DriftReport] = []

        for name in self.artefacts(document):
            path = self.output_directory / name
            expected = recorded.get(name)

            if not path.is_file():
                status = STATUS_MISSING
                actual = None
            else:
                actual = _digest(path.read_bytes())
                if expected is None:
                    # A file the appliance has never written is not the
                    # appliance's to overwrite.
                    status = STATUS_UNMANAGED
                elif actual == expected:
                    status = STATUS_CURRENT
                else:
                    status = STATUS_MODIFIED

            reports.append(
                DriftReport(
                    name=name,
                    path=str(path),
                    status=status,
                    recorded_digest=expected,
                    actual_digest=actual,
                )
            )
        return reports

    def render(
        self,
        document: Mapping[str, Any] | None = None,
        force: bool = False,
    ) -> dict[str, Any]:
        """Write every artefact, refusing to overwrite a diverged file.

        With ``force`` the divergence is overwritten deliberately, which is the
        regenerate arm of the reconciliation decision.  The refusal path is the
        default because losing an administrator's emergency edit without
        telling them is the exact failure this product exists to remove.
        """
        source = document if document is not None else self.load()
        rendered = self.artefacts(source)
        reports = self.inspect(source)
        diverged = [report for report in reports if report.diverged]

        if diverged and not force:
            for report in diverged:
                _LOG.error(
                    "the generated file named %s diverged from the appliance record "
                    "and was not overwritten",
                    report.name,
                )
            raise DriftDetected(diverged)

        self.output_directory.mkdir(parents=True, exist_ok=True)
        digests = self._load_digests()
        written: list[str] = []

        for name, content in rendered.items():
            path = self.output_directory / name
            digest = _digest(content.encode("utf-8"))
            if path.is_file() and _digest(path.read_bytes()) == digest:
                # Identical content is not rewritten, so an unchanged render
                # does not disturb file timestamps the engine may watch.
                digests[name] = digest
                continue
            _atomic_write(path, content)
            digests[name] = digest
            written.append(name)

        self._save_digests(digests)
        if written:
            _LOG.info(
                "the appliance rendered %d configuration file or files: %s",
                len(written),
                ", ".join(written),
            )
        return {
            "written": written,
            "unchanged": [name for name in rendered if name not in written],
            "forced": bool(force and diverged),
            "reports": [report.as_dict() for report in reports],
        }

    def adopt(self, name: str) -> DriftReport:
        """Accept the on disk version of an artefact as the current record.

        This is the adopt arm of the reconciliation decision.  The appliance
        records the administrator's file as authoritative, which stops the
        divergence being reported without destroying the edit.
        """
        path = self.output_directory / name
        if not path.is_file():
            raise FileNotFoundError(f"there is no artefact named {name} to adopt")

        digests = self._load_digests()
        actual = _digest(path.read_bytes())
        digests[name] = actual
        self._save_digests(digests)
        _LOG.warning(
            "the on disk version of the file named %s was adopted as authoritative; "
            "the appliance will no longer report it as diverged",
            name,
        )
        return DriftReport(
            name=name,
            path=str(path),
            status=STATUS_CURRENT,
            recorded_digest=actual,
            actual_digest=actual,
        )

    # -- digest bookkeeping -------------------------------------------------

    def _load_digests(self) -> dict[str, str]:
        if not self.digest_path.is_file():
            return {}
        try:
            data = json.loads(self.digest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            _LOG.warning(
                "the rendered file digest record could not be read; every generated "
                "file will be treated as unmanaged until it is reconciled"
            )
            return {}
        return {str(key): str(value) for key, value in data.items()} if isinstance(data, dict) else {}

    def _save_digests(self, digests: Mapping[str, str]) -> None:
        _atomic_write(self.digest_path, json.dumps(dict(digests), indent=2, sort_keys=True))


# -- renderers -------------------------------------------------------------


def _header(title: str) -> str:
    return (
        f"; {title}\n"
        f"; {GENERATED_MARKER}\n"
        "; edits made here are detected by the appliance and raised for an\n"
        "; explicit reconciliation decision rather than being silently replaced.\n"
        ";\n"
        "; this appliance assigns no addresses: it contains no address allocation\n"
        "; service of any kind, by specification.\n"
        "\n"
    )


def render_trunk_configuration(document: Mapping[str, Any]) -> str:
    """Render the trunk definitions for the session protocol channel driver."""
    lines = [_header("trunk definitions")]
    lines.append("[global]\n")
    lines.append("type = global\n")
    lines.append("user_agent = Legacy-to-Modern IPBX Appliance\n\n")

    for trunk in document.get("trunks", []) or []:
        name = str(trunk.get("name", "")).strip()
        if not name:
            continue
        host = str(trunk.get("host", "")).strip()
        username = str(trunk.get("username", "")).strip()

        lines.append(f"[{name}]\n")
        lines.append("type = registration\n")
        lines.append(f"outbound_auth = {name}-auth\n")
        lines.append(f"server_uri = sip:{host}\n")
        lines.append(f"client_uri = sip:{username}@{host}\n")
        lines.append("retry_interval = 60\n")
        lines.append("forbidden_retry_interval = 600\n")
        lines.append("expiration = 3600\n\n")

        lines.append(f"[{name}-auth]\n")
        lines.append("type = auth\n")
        lines.append("auth_type = userpass\n")
        lines.append(f"username = {username}\n")
        lines.append("; the secret is injected at deployment time and is never rendered here\n\n")

        lines.append(f"[{name}-endpoint]\n")
        lines.append("type = endpoint\n")
        lines.append(
            f"context = {document.get('dialplan', {}).get('inbound_context', 'from-trunk')}\n"
        )
        lines.append("disallow = all\n")
        lines.append("allow = ulaw,alaw\n")
        lines.append(f"outbound_auth = {name}-auth\n")
        lines.append(f"aors = {name}-aor\n\n")

        lines.append(f"[{name}-aor]\n")
        lines.append("type = aor\n")
        lines.append(f"contact = sip:{host}\n\n")

    return "".join(lines)


def render_dialplan(document: Mapping[str, Any]) -> str:
    """Render the dialplan from the declared extensions."""
    dialplan = document.get("dialplan", {}) or {}
    internal = str(dialplan.get("internal_context", "internal"))
    inbound = str(dialplan.get("inbound_context", "from-trunk"))

    lines = [_header("dialplan")]
    lines.append(f"[{internal}]\n")
    for entry in document.get("extensions", []) or []:
        number = str(entry.get("number", "")).strip()
        target = str(entry.get("target", "")).strip()
        if not number or not target:
            continue
        lines.append(f"exten => {number},1,NoOp(a call to the extension {number})\n")
        lines.append(f" same => n,Dial({target},20)\n")
        lines.append(" same => n,Voicemail(${EXTEN}@default,u)\n")
        lines.append(" same => n,Hangup()\n\n")

    lines.append(f"\n[{inbound}]\n")
    inbound_target = str(dialplan.get("inbound_target", "")).strip()
    if inbound_target:
        lines.append("exten => _.,1,NoOp(an inbound call from a trunk)\n")
        lines.append(f" same => n,Goto({internal},{inbound_target},1)\n\n")
    else:
        lines.append("exten => _.,1,NoOp(an inbound call with no destination configured)\n")
        lines.append(" same => n,Congestion(5)\n")
        lines.append(" same => n,Hangup()\n\n")

    return "".join(lines)


def render_hardware_channels(document: Mapping[str, Any]) -> str:
    """Render the legacy interface card channel configuration."""
    hardware = document.get("hardware", {}) or {}
    dialplan = document.get("dialplan", {}) or {}
    context = str(dialplan.get("inbound_context", "from-trunk"))

    lines = [_header("legacy interface card channels")]
    lines.append("[channels]\n")
    lines.append("language = en\n")
    lines.append(f"context = {context}\n")
    lines.append("signalling = fxo_ks\n")
    lines.append("echocancel = yes\n")
    lines.append("echocancelwhenbridged = no\n")
    lines.append("rxgain = 0.0\n")
    lines.append("txgain = 0.0\n")
    lines.append("immediate = no\n\n")

    spans = hardware.get("spans", []) or []
    if not spans:
        lines.append("; no span has been mapped to a logical trunk yet.  run the guided\n")
        lines.append("; hardware bring up from the dashboard to map detected spans.\n")
        return "".join(lines)

    for span in spans:
        number = span.get("number")
        signalling = str(span.get("signalling", "fxo_ks"))
        channels = str(span.get("channels", "")).strip()
        if number is None or not channels:
            continue
        lines.append(f"; span number {number}\n")
        lines.append(f"signalling = {signalling}\n")
        group = span.get("group")
        if group is not None:
            lines.append(f"group = {group}\n")
        lines.append(f"channel => {channels}\n\n")

    return "".join(lines)


def render_manager_interface(document: Mapping[str, Any]) -> str:
    """Render the engine manager interface configuration.

    The interface is bound to the loopback address only.  The control plane is
    the sole consumer and it runs on the same machine, so exposing the manager
    interface to the network would add risk and no capability.
    """
    manager = document.get("manager", {}) or {}
    username = str(manager.get("username", "myipbx"))

    lines = [_header("engine manager interface")]
    lines.append("[general]\n")
    lines.append("enabled = yes\n")
    lines.append("webenabled = no\n")
    lines.append("port = 5038\n")
    lines.append("bindaddr = 127.0.0.1\n")
    lines.append("displayconnects = yes\n")
    lines.append("timestampevents = yes\n\n")

    lines.append(f"[{username}]\n")
    lines.append("; the secret is injected at deployment time and is never rendered here\n")
    lines.append("deny = 0.0.0.0/0.0.0.0\n")
    lines.append("permit = 127.0.0.1/255.255.255.255\n")
    lines.append("read = system,call,log,verbose,agent,user,config,dtmf,reporting,cdr,dialplan\n")
    lines.append("write = system,call,agent,user,config,command,reporting,originate\n")
    return "".join(lines)


# -- helpers ---------------------------------------------------------------


def _digest(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _atomic_write(path: Path, content: str) -> None:
    """Write a file atomically within its own directory."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".partial")
    try:
        with open(temporary, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
