#!/usr/bin/env bash
# Stage two -- static network configuration and the address allocation audit.
#
# Constraint One in its build time and install time form.  This stage installs
# no address allocation service, configures every interface with a static
# address, and refuses to proceed if an allocation service is found on the
# machine by any of the audit's five detections.
#
# The appliance is a guest on someone else's network.  It accepts an address
# from that network's own administration and never offers one to anybody.

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

STAGE="stage-two-network-static"

# Supplied by the operator, by the installer, or by the environment.  There is
# deliberately no discovery path here: an appliance that guesses its own
# address is an appliance that fights the network it was placed on.
APPLIANCE_INTERFACE="${APPLIANCE_INTERFACE:-}"
APPLIANCE_ADDRESS="${APPLIANCE_ADDRESS:-}"
APPLIANCE_PREFIX_LENGTH="${APPLIANCE_PREFIX_LENGTH:-24}"
APPLIANCE_GATEWAY="${APPLIANCE_GATEWAY:-}"
APPLIANCE_RESOLVERS="${APPLIANCE_RESOLVERS:-}"

TEMPLATE_DIR="${SCRIPT_DIR}/../config/network"

audit_the_machine() {
    local audit="${SCRIPT_DIR}/verify-no-dhcp.sh"
    [[ -x "${audit}" ]] || fail "the address allocation audit script is missing or is not executable"

    log_info "running the address allocation exclusion audit before touching the network"
    if ! "${audit}"; then
        fail "this machine allocates addresses; remove the allocation service before installing the appliance"
    fi
    log_info "the audit passed: this machine assigns no addresses"
}

detect_network_manager() {
    if [[ -d /etc/netplan ]] && have_command netplan; then
        printf 'netplan'
    elif have_command nmcli; then
        printf 'network-manager'
    elif [[ -d /etc/systemd/network ]] && have_command networkctl; then
        printf 'systemd-networkd'
    elif [[ -f /etc/network/interfaces ]]; then
        printf 'interfaces-file'
    else
        printf 'unknown'
    fi
}

require_static_parameters() {
    [[ -n "${APPLIANCE_INTERFACE}" ]] || fail "the interface name must be supplied; the appliance does not guess it"
    [[ -n "${APPLIANCE_ADDRESS}" ]] || fail "the static address must be supplied; the appliance never requests one"
    [[ -n "${APPLIANCE_GATEWAY}" ]] || log_warn "no gateway was supplied; the appliance will reach only its own network segment"

    if ! [[ "${APPLIANCE_PREFIX_LENGTH}" =~ ^[0-9]+$ ]] \
        || (( APPLIANCE_PREFIX_LENGTH < 1 || APPLIANCE_PREFIX_LENGTH > 32 )); then
        fail "the prefix length is not a usable value"
    fi
}

render_netplan() {
    local destination="/etc/netplan/60-crossbar-static.yaml"
    log_info "writing a static configuration for the interface named ${APPLIANCE_INTERFACE} to ${destination}"

    if is_rehearsal; then
        log_info "rehearsal: the static configuration would be written but no file is created"
        return 0
    fi

    local resolvers_block=""
    if [[ -n "${APPLIANCE_RESOLVERS}" ]]; then
        resolvers_block="      nameservers:
        addresses: [${APPLIANCE_RESOLVERS}]"
    fi

    local routes_block=""
    if [[ -n "${APPLIANCE_GATEWAY}" ]]; then
        routes_block="      routes:
        - to: default
          via: ${APPLIANCE_GATEWAY}"
    fi

    # The absence of an address request directive here is the point of this
    # stage.  Every address on this appliance is written down, never asked for.
    cat >"${destination}" <<EOF
# ${APPLIANCE_NAME} -- static network configuration
# generated by the appliance installer
#
# this appliance requests no address and offers no address.  there is no
# address allocation client directive and no address allocation service on
# this machine, by product specification.
network:
  version: 2
  renderer: networkd
  ethernets:
    ${APPLIANCE_INTERFACE}:
      addresses:
        - ${APPLIANCE_ADDRESS}/${APPLIANCE_PREFIX_LENGTH}
${routes_block}
${resolvers_block}
EOF
    run_command chmod 0600 "${destination}"
    log_info "the static configuration was written; apply it with the netplan apply command when ready"
}

render_systemd_networkd() {
    local destination="/etc/systemd/network/60-crossbar-static.network"
    log_info "writing a static configuration for the interface named ${APPLIANCE_INTERFACE} to ${destination}"

    if is_rehearsal; then
        log_info "rehearsal: the static configuration would be written but no file is created"
        return 0
    fi

    {
        printf '# %s -- static network configuration\n' "${APPLIANCE_NAME}"
        printf '# this appliance requests no address and offers no address.\n\n'
        printf '[Match]\nName=%s\n\n' "${APPLIANCE_INTERFACE}"
        printf '[Network]\n'
        printf 'Address=%s/%s\n' "${APPLIANCE_ADDRESS}" "${APPLIANCE_PREFIX_LENGTH}"
        if [[ -n "${APPLIANCE_GATEWAY}" ]]; then
            printf 'Gateway=%s\n' "${APPLIANCE_GATEWAY}"
        fi
        local resolver
        for resolver in ${APPLIANCE_RESOLVERS//,/ }; do
            printf 'DNS=%s\n' "${resolver}"
        done
        printf 'LinkLocalAddressing=no\n'
        printf 'IPv6AcceptRA=no\n'
    } >"${destination}"

    run_command chmod 0644 "${destination}"
}

render_interfaces_file() {
    local destination="/etc/network/interfaces.d/60-crossbar-static"
    ensure_directory "$(dirname "${destination}")"
    log_info "writing a static configuration for the interface named ${APPLIANCE_INTERFACE} to ${destination}"

    if is_rehearsal; then
        log_info "rehearsal: the static configuration would be written but no file is created"
        return 0
    fi

    {
        printf '# %s -- static network configuration\n' "${APPLIANCE_NAME}"
        printf '# this appliance requests no address and offers no address.\n\n'
        printf 'auto %s\n' "${APPLIANCE_INTERFACE}"
        printf 'iface %s inet static\n' "${APPLIANCE_INTERFACE}"
        printf '    address %s\n' "${APPLIANCE_ADDRESS}"
        printf '    netmask /%s\n' "${APPLIANCE_PREFIX_LENGTH}"
        if [[ -n "${APPLIANCE_GATEWAY}" ]]; then
            printf '    gateway %s\n' "${APPLIANCE_GATEWAY}"
        fi
    } >"${destination}"
}

apply_static_configuration() {
    local manager
    manager="$(detect_network_manager)"
    log_info "the detected network configuration system is ${manager}"

    case "${manager}" in
        netplan) render_netplan ;;
        systemd-networkd) render_systemd_networkd ;;
        interfaces-file) render_interfaces_file ;;
        network-manager)
            log_info "configuring a static profile through the network manager command line"
            run_command nmcli connection modify "${APPLIANCE_INTERFACE}" \
                ipv4.method manual \
                ipv4.addresses "${APPLIANCE_ADDRESS}/${APPLIANCE_PREFIX_LENGTH}"
            if [[ -n "${APPLIANCE_GATEWAY}" ]]; then
                run_command nmcli connection modify "${APPLIANCE_INTERFACE}" \
                    ipv4.gateway "${APPLIANCE_GATEWAY}"
            fi
            ;;
        *)
            log_warn "the network configuration system was not recognised"
            log_warn "configure the interface named ${APPLIANCE_INTERFACE} with the static address ${APPLIANCE_ADDRESS} by hand"
            if [[ -d "${TEMPLATE_DIR}" ]]; then
                log_warn "reference templates are available in the directory at ${TEMPLATE_DIR}"
            fi
            ;;
    esac
}

main() {
    banner "stage two -- static network configuration"
    require_root

    if skip_if_completed "${STAGE}"; then
        return 0
    fi

    log_step "auditing the machine for an address allocation service"
    audit_the_machine

    if [[ -z "${APPLIANCE_INTERFACE}" && -z "${APPLIANCE_ADDRESS}" ]]; then
        log_warn "no static addressing parameters were supplied; the existing network configuration is left untouched"
        log_warn "the appliance neither requests nor offers an address in either case"
        mark_stage_completed "${STAGE}" "the existing static configuration was left in place"
        return 0
    fi

    log_step "validating the supplied static parameters"
    require_static_parameters

    log_step "writing the static configuration"
    apply_static_configuration

    log_step "re-auditing after the configuration change"
    audit_the_machine

    mark_stage_completed "${STAGE}" "the interface is statically addressed and no allocation service exists"
    log_info "stage two is complete"
}

main "$@"
